/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Teclado;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rodri
 */
public class GerenciaTeclado extends javax.swing.JFrame {

    private Teclado objTeclado;

    public GerenciaTeclado() {
        initComponents();
        this.objTeclado = new Teclado();
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTeclado_GT = new javax.swing.JTable();
        b_cancelar_GT = new javax.swing.JButton();
        b_deletar_GT = new javax.swing.JButton();
        b_alterar_GT = new javax.swing.JButton();
        Label_nome_GT = new javax.swing.JLabel();
        nome_GT = new javax.swing.JTextField();
        Label_marca_GT = new javax.swing.JLabel();
        marca_GT = new javax.swing.JTextField();
        Label_modelo_GT = new javax.swing.JLabel();
        modelo_GT = new javax.swing.JTextField();
        Label_preco_GT = new javax.swing.JLabel();
        preco_GT = new javax.swing.JTextField();
        Label_qtdestoque_GT = new javax.swing.JLabel();
        qtdestoque_GT = new javax.swing.JTextField();
        Label_dimensao_GT = new javax.swing.JLabel();
        dimensao_GT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        conectividade_GT = new javax.swing.JTextField();
        Label_descricao_GT = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricao_GT = new javax.swing.JTextArea();
        datacadastro_GT = new com.toedter.calendar.JDateChooser();
        Label_datacadastro_GT = new javax.swing.JLabel();
        Label_tipo_GT = new javax.swing.JLabel();
        tipo_GT = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(883, 591));
        getContentPane().setLayout(null);

        jTableTeclado_GT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Tipo", "Marca", "Modelo", "Preço", "Quant. Estoque", "Data de cadastro", "Descrição", "Dimensão", "Conectividade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTeclado_GT.getTableHeader().setReorderingAllowed(false);
        jTableTeclado_GT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTeclado_GTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTeclado_GT);
        if (jTableTeclado_GT.getColumnModel().getColumnCount() > 0) {
            jTableTeclado_GT.getColumnModel().getColumn(0).setResizable(false);
            jTableTeclado_GT.getColumnModel().getColumn(1).setResizable(false);
            jTableTeclado_GT.getColumnModel().getColumn(2).setResizable(false);
            jTableTeclado_GT.getColumnModel().getColumn(3).setResizable(false);
            jTableTeclado_GT.getColumnModel().getColumn(4).setResizable(false);
            jTableTeclado_GT.getColumnModel().getColumn(5).setResizable(false);
            jTableTeclado_GT.getColumnModel().getColumn(6).setResizable(false);
            jTableTeclado_GT.getColumnModel().getColumn(7).setResizable(false);
            jTableTeclado_GT.getColumnModel().getColumn(8).setResizable(false);
            jTableTeclado_GT.getColumnModel().getColumn(9).setResizable(false);
            jTableTeclado_GT.getColumnModel().getColumn(10).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 820, 120);

        b_cancelar_GT.setText("Cancelar");
        b_cancelar_GT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelar_GTActionPerformed(evt);
            }
        });
        getContentPane().add(b_cancelar_GT);
        b_cancelar_GT.setBounds(200, 490, 90, 25);

        b_deletar_GT.setText("Deletar");
        b_deletar_GT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deletar_GTActionPerformed(evt);
            }
        });
        getContentPane().add(b_deletar_GT);
        b_deletar_GT.setBounds(380, 490, 80, 25);

        b_alterar_GT.setText("Alterar");
        b_alterar_GT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_alterar_GTActionPerformed(evt);
            }
        });
        getContentPane().add(b_alterar_GT);
        b_alterar_GT.setBounds(550, 490, 80, 25);

        Label_nome_GT.setText("Nome do produto:");
        getContentPane().add(Label_nome_GT);
        Label_nome_GT.setBounds(130, 230, 99, 16);
        getContentPane().add(nome_GT);
        nome_GT.setBounds(230, 230, 199, 22);

        Label_marca_GT.setText("Marca: ");
        getContentPane().add(Label_marca_GT);
        Label_marca_GT.setBounds(150, 260, 39, 16);
        getContentPane().add(marca_GT);
        marca_GT.setBounds(190, 260, 160, 22);

        Label_modelo_GT.setText("Modelo:");
        getContentPane().add(Label_modelo_GT);
        Label_modelo_GT.setBounds(140, 290, 44, 16);
        getContentPane().add(modelo_GT);
        modelo_GT.setBounds(190, 290, 160, 22);

        Label_preco_GT.setText("Preço:");
        getContentPane().add(Label_preco_GT);
        Label_preco_GT.setBounds(150, 320, 44, 16);
        getContentPane().add(preco_GT);
        preco_GT.setBounds(190, 320, 92, 22);

        Label_qtdestoque_GT.setText("Quant. Estoque:");
        getContentPane().add(Label_qtdestoque_GT);
        Label_qtdestoque_GT.setBounds(100, 350, 84, 16);
        getContentPane().add(qtdestoque_GT);
        qtdestoque_GT.setBounds(190, 350, 90, 22);

        Label_dimensao_GT.setText("Dimensão: ");
        getContentPane().add(Label_dimensao_GT);
        Label_dimensao_GT.setBounds(460, 230, 78, 16);
        getContentPane().add(dimensao_GT);
        dimensao_GT.setBounds(530, 230, 153, 22);

        jLabel1.setText("Conectividade:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 260, 79, 16);
        getContentPane().add(conectividade_GT);
        conectividade_GT.setBounds(530, 260, 153, 22);

        Label_descricao_GT.setText("Descrição (opcional):");
        getContentPane().add(Label_descricao_GT);
        Label_descricao_GT.setBounds(400, 300, 120, 16);

        descricao_GT.setColumns(20);
        descricao_GT.setRows(5);
        jScrollPane2.setViewportView(descricao_GT);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(530, 300, 230, 90);
        getContentPane().add(datacadastro_GT);
        datacadastro_GT.setBounds(190, 390, 126, 22);

        Label_datacadastro_GT.setText("Data de cadastro:");
        getContentPane().add(Label_datacadastro_GT);
        Label_datacadastro_GT.setBounds(90, 390, 110, 16);

        Label_tipo_GT.setText("Tipo:");
        getContentPane().add(Label_tipo_GT);
        Label_tipo_GT.setBounds(690, 190, 50, 16);

        tipo_GT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teclado" }));
        getContentPane().add(tipo_GT);
        tipo_GT.setBounds(730, 190, 100, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_alterar_GTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alterar_GTActionPerformed

        try {

            // recebendo e validando dados da interface gr�fica.
            int id = 0;
            String nome_teclado = "";
            String marca_teclado = "";
            String modelo_teclado = "";
            float preco_teclado = 0;
            int qtd_estoque_teclado = 0;
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String datacadastro_teclado = sdf.format(datacadastro_GT.getDate());
            String descricao_teclado = "";
            String dimensao_teclado = "";
            String conectividade_teclado = "";
            String tipo_teclado;

            if (this.nome_GT.getText().length() < 2 || this.nome_GT.getText().length() > 45) {
                throw new Mensagens("Nome deve conter entre DOIS a QUARENTA E CINCO caracteres!");
            } else {
                nome_teclado = this.nome_GT.getText();
            }
            if (this.tipo_GT.getSelectedItem() == "Teclado") {
                tipo_teclado = this.tipo_GT.getSelectedItem().toString();
            } else {
                throw new Mensagens("Tipo de produto inválido!");
            }

            if (this.marca_GT.getText().length() < 2 || this.marca_GT.getText().length() > 45) {
                throw new Mensagens("A declaração de marca deve conter entre DOIS a QUARENTA E CINCO caracteres!");
            } else {
                marca_teclado = this.marca_GT.getText();
            }

            if (this.modelo_GT.getText().length() < 2 || this.modelo_GT.getText().length() > 45) {
                throw new Mensagens("A declaração de modelo deve conter entre DOIS a QUARENTA E CINCO caracteres!");
            } else {
                modelo_teclado = this.modelo_GT.getText();
            }

            if (this.preco_GT.getText().length() < 1 || this.preco_GT.getText().length() > 50000) {
                throw new Mensagens("O preço não pode ser menor que UM ou maior que CINQUENTA MIL!");
            } else {
                preco_teclado = Float.parseFloat(this.preco_GT.getText());
            }

            if (this.qtdestoque_GT.getText().length() <= 0) {
                throw new Mensagens("O estoque não pode ser ZERO!");

            } else {
                qtd_estoque_teclado = Integer.parseInt(this.qtdestoque_GT.getText());
            }

            if (this.datacadastro_GT.getDate() == null) {
                throw new Mensagens("A data precisa ser selecionada!");

            } else {
                datacadastro_teclado = sdf.format(this.datacadastro_GT.getDate());
            }
            if (this.descricao_GT.getText().length() > 250) {
                throw new Mensagens("Descrição muito longa! Máximo 250 caracteres!");
            }
            descricao_teclado = this.descricao_GT.getText();

            if (this.dimensao_GT.getText().length() < 0 || this.dimensao_GT.getText().length() > 50) {
                throw new Mensagens("O campo de dimensão deve conter de UM até 50 caracteres!");
            } else {
                dimensao_teclado = this.dimensao_GT.getText();
            }
            if (this.conectividade_GT.getText().length() < 0 || this.dimensao_GT.getText().length() > 100) {
                throw new Mensagens("O campo de conectividade deve conter de UM até 50 caracteres!");
            } else {
                conectividade_teclado = this.conectividade_GT.getText();
            }
            if (this.jTableTeclado_GT.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Aluno para Alterar");
            } else {
                id = Integer.parseInt(this.jTableTeclado_GT.getValueAt(this.jTableTeclado_GT.getSelectedRow(), 0).toString());
            }

            if (this.objTeclado.UpdateTecladoBD (dimensao_teclado, conectividade_teclado, id, nome_teclado, tipo_teclado, preco_teclado, descricao_teclado, marca_teclado, modelo_teclado, qtd_estoque_teclado, datacadastro_teclado)) {
                JOptionPane.showMessageDialog(rootPane, "Teclado Alterado com Sucesso!");

                this.nome_GT.setText("");
                this.marca_GT.setText("");
                this.modelo_GT.setText("");
                this.preco_GT.setText("");
                this.qtdestoque_GT.setText("");
                this.datacadastro_GT.setDate(null);
                this.descricao_GT.setText("");
                this.dimensao_GT.setText("");
                this.conectividade_GT.setText("");
                this.tipo_GT.setSelectedItem("Teclado");
            }
            System.out.println(this.objTeclado.getListaTeclado().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Preencha o campo usando números!");
        }catch (NullPointerException erroNull) {
            JOptionPane.showMessageDialog(null, "Preencha o campo data!");
        } catch (SQLException ex) {
            Logger.getLogger(GerenciaTeclado.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            // atualiza a tabela.
            carregaTabela();
        }
        /*catch (SQLException ex) {
        Logger.getLogger(CadastroTeclado.class.getName()).log(Level.SEVERE, null, ex);
        }*/ 
        /*catch (SQLException ex) {
Logger.getLogger(CadastroTeclado.class.getName()).log(Level.SEVERE, null, ex);
}*/
    }//GEN-LAST:event_b_alterar_GTActionPerformed

    private void b_cancelar_GTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelar_GTActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_b_cancelar_GTActionPerformed

    private void b_deletar_GTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deletar_GTActionPerformed

        try {
            // validando dados da interface gr�fica.
            int id = 0;
            if (this.jTableTeclado_GT.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Teclado para APAGAR");
            } else {
                id = Integer.parseInt(this.jTableTeclado_GT.getValueAt(this.jTableTeclado_GT.getSelectedRow(), 0).toString());
            }
            // retorna 0 -> primeiro bot�o | 1 -> segundo bot�o | 2 -> terceiro bot�o
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR este Teclado?");

            if (resposta_usuario == 0) {// clicou em SIM

                // envia os dados para o Teclado processar
                if (this.objTeclado.DeleteTecladoBD(id)) {

                    // limpa os campos
                    this.nome_GT.setText("");
                    this.tipo_GT.setSelectedItem("Teclado");
                    this.marca_GT.setText("");
                    this.modelo_GT.setText("");
                    this.preco_GT.setText("");
                    this.qtdestoque_GT.setText("");
                    this.datacadastro_GT.setDate(null);
                    this.descricao_GT.setText("");
                    this.dimensao_GT.setText("");
                    this.conectividade_GT.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Teclado Apagado com Sucesso!");

                }

            }
            System.out.println(this.objTeclado.getListaTeclado().toString());

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();

        }
    }//GEN-LAST:event_b_deletar_GTActionPerformed

    private void jTableTeclado_GTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTeclado_GTMouseClicked
     
        
        if (this.jTableTeclado_GT.getSelectedRow() != -1) {

            String nome = this.jTableTeclado_GT.getValueAt(this.jTableTeclado_GT.getSelectedRow(), 1).toString();
            String tipo = this.jTableTeclado_GT.getValueAt(this.jTableTeclado_GT.getSelectedRow(), 2).toString();
            String marca = this.jTableTeclado_GT.getValueAt(this.jTableTeclado_GT.getSelectedRow(), 3).toString();
            String modelo = this.jTableTeclado_GT.getValueAt(this.jTableTeclado_GT.getSelectedRow(), 4).toString();
            String preco = this.jTableTeclado_GT.getValueAt(this.jTableTeclado_GT.getSelectedRow(), 5).toString();
            String qtd_estoque = this.jTableTeclado_GT.getValueAt(this.jTableTeclado_GT.getSelectedRow(), 6).toString();
            String data_cadastroString = this.jTableTeclado_GT.getValueAt(this.jTableTeclado_GT.getSelectedRow(), 7).toString();
            String descricao = this.jTableTeclado_GT.getValueAt(this.jTableTeclado_GT.getSelectedRow(), 8).toString();
            String dimensao = this.jTableTeclado_GT.getValueAt(this.jTableTeclado_GT.getSelectedRow(), 9).toString();
            String conectividade = this.jTableTeclado_GT.getValueAt(this.jTableTeclado_GT.getSelectedRow(), 10).toString();
            Date data_cadastro = null;
           
            
            
            this.nome_GT.setText(nome);
            this.tipo_GT.setSelectedItem(tipo);
            this.marca_GT.setText(marca);
            this.modelo_GT.setText(modelo);
            this.preco_GT.setText(preco);
            this.qtdestoque_GT.setText(qtd_estoque);
             try {
                data_cadastro = new SimpleDateFormat("dd/MM/yyyy").parse(data_cadastroString);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao converter a data: ");               
            }
           
            this.descricao_GT.setText(descricao);
            this.dimensao_GT.setText(dimensao);
            this.conectividade_GT.setText(conectividade);

        }
    }//GEN-LAST:event_jTableTeclado_GTMouseClicked

    public void carregaTabela() {

        DefaultTableModel modelo = (DefaultTableModel) this.jTableTeclado_GT.getModel();
        modelo.setNumRows(0);

        ArrayList<Teclado> listaTeclado = new ArrayList<>();
        listaTeclado = objTeclado.getListaTeclado();

        for (Teclado a : listaTeclado) {
            modelo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getTipo(),
                a.getMarca(),
                a.getModelo(),
                a.getPreco(),
                a.getQtd_estoque(),
                a.getData_cadastro(),
                a.getDescricao(),
                a.getDimensao(),
                a.getConectividade(),
            });
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaTeclado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_datacadastro_GT;
    private javax.swing.JLabel Label_descricao_GT;
    private javax.swing.JLabel Label_dimensao_GT;
    private javax.swing.JLabel Label_marca_GT;
    private javax.swing.JLabel Label_modelo_GT;
    private javax.swing.JLabel Label_nome_GT;
    private javax.swing.JLabel Label_preco_GT;
    private javax.swing.JLabel Label_qtdestoque_GT;
    private javax.swing.JLabel Label_tipo_GT;
    private javax.swing.JButton b_alterar_GT;
    private javax.swing.JButton b_cancelar_GT;
    private javax.swing.JButton b_deletar_GT;
    private javax.swing.JTextField conectividade_GT;
    private com.toedter.calendar.JDateChooser datacadastro_GT;
    private javax.swing.JTextArea descricao_GT;
    private javax.swing.JTextField dimensao_GT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTeclado_GT;
    private javax.swing.JTextField marca_GT;
    private javax.swing.JTextField modelo_GT;
    private javax.swing.JTextField nome_GT;
    private javax.swing.JTextField preco_GT;
    private javax.swing.JTextField qtdestoque_GT;
    private javax.swing.JComboBox<String> tipo_GT;
    // End of variables declaration//GEN-END:variables
}
